apiVersion: v1
kind: Service
metadata:
  name: mylb-service
spec:
  selector:
    env: dev
  type: LoadBalancer  
  ports:
    - name: nginx-app1
      protocol: TCP
      port: 8085
      targetPort: 8085
    - name: nginx-app2
      protocol: TCP
      port: 8089
      targetPort: 8089